apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio # Matches the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80 # The port the world sees
      targetPort: 3000 # The port your container listens on
  type: LoadBalancer # "Real World" Power: Distribute traffic across all 3 replicas
